function [lg,ll,l2,t2]=legdisp(varargin)
% function [lg,ll,l2,t2]=legdisp([opts])
%
%     Display legend for line handles that carry a DisplayName.
%     returns legend handle lg, ll are the existing line handles 
%     from the current axis set that were used for the legend,
%     and l2 are the line handles e.g. returned by MatLab's legend()
%     or generated by -detach within the legend axis set.
%
% Options
%
%     'pick',.   pick (sub)set in given order []
%                negative indices pick from the end (-1=end)
%     '~pick',.  exclude specified (sub)set from legend
%     '-flip'    flip order of entries (if -flip and pick are specified
%                then pick is done on the flipped handle set!)
%
%     '-detach'  detach legend from axis (allows to create another legend)
%     '-erase'   white background but no border
%                in case grid lines are still through legend, use -detach
%     '-eraset'  white background for text labels only
%     '-rm'      remove old legdisp axes sets
%
%     'xsc',..   scale legend horizontally (e.g. shrink if xsc<1)
%     'ysc',..   scale legend vertically (e.g. shrink if ysc<1)
%     'dx',...   shift of legend box / axis set
%     'dy',...   call to leg_mvtext if non-empty.
%     
%     'topt',..  further text options
%     'fs',..    font size of legend entries
%     
%     All remaining options will be handed over to legend(...,OPTS).
%
% Usage #2: funtion [m,ll]=legdisp('-count');
%
%    Get count and handles of line objects with non-empty disp only.
%
% Wb,Oct05,05 ; Wb,Aug04,16

% NB! starting matlab>2013b legend is no longer of axis type,
%     but is an object type of its own
%  => for old version, see Archive/legdisp_160801.m
%  => in case of detach, move to new axis handle
% NB! Starting matlab/R2017a, legend will auto-update if present
% To prevent this behavior, set the legends "AutoUpdate" property.

  lg=[]; ll=[]; l2=[]; t2=[];

  if nargin==1 && isequal(varargin{1},'-count')
     ll=findall(gca,'type','line','-not','Disp','');
     l2=findall(gca,'type','patch','-not','Disp',''); ll=[ll;l2];
     lg=numel(ll); return
  end

  if nargin && iscell(varargin{1})
     if numel(varargin{1})==2 && isnumeric(varargin{1}{2})
        pos=varargin{1}{1};
        dx=varargin{1}{2};
     else
        [pos,dx]=postrans('--leg',varargin{1});
     end
     varargin(1)=[];
  else pos=''; dx=[]; end

  erase=0;

  getopt('init',varargin);
     flip   = getopt('-flip'  );
     pick   = getopt('pick',{});

     pickE  = getopt('pickE',{});

     pickX  = getopt('~pick',{});
     detach = getopt('-detach');
     rmold  = getopt('-rm');
     xsc    = getopt('xsc',[]);
     ysc    = getopt('ysc',[]);
     xl     = getopt('xl',[]);
     dx     = getopt('dx',dx);
     dy     = getopt('dy',[]);

     topt   = getopt('topt',{});
     fs     = getopt('fs',[]);

     if getopt('-eraset'), erase=bitor(erase,1); end
     if getopt('-erase' ), erase=bitor(erase,2); end

  varargin=getopt('get_remaining');
  if ~isempty(pos)
  varargin={'Location',pos,varargin{:}}; end

  q=[~isempty(pick), ~isempty(pickE), ~isempty(pickX)];
  if sum(q)>1, wbdie(...
    'invalid usage (got multiple requests for pick* !?'); end

  if isempty(pick) && ~iscell(pick)
     if ~nargout, clear lg; end
     return
  end

  ah=gca; o={'type','line','visible','on'};

  lh=flipud(findall(ah,o{:}));
  l2=flipud(findall(ah,'type','patch',o{3:end}));
  if ~isempty(l2), lh=[lh; l2]; end

  h=findall(ah,o{:},'tag','arrowsafe');
  if ~isempty(h)
     [q,is]=setdiff(lh,h);
     lh=lh(sort(is));
  end

  nn=get(lh,'DisplayName'); if length(lh)==1, nn={nn}; end
  n=length(lh); m=zeros(1,n);

  for i=1:n
     if ~isempty(nn{i}) && isempty(regexp(nn{i},'^data\d+$')), m(i)=1;
        nn{i}=regexprep(nn{i},'^getcolumn\((.*),([0-9])\)','$1(:,$2)');
     end
  end

  ii=find(m); if flip, ii=fliplr(ii); end
  n=numel(ii);

  if ~isempty(pickE)
     pick=(n+1)-flipud(pickE(:));
  elseif isnumeric(pick)
     i=find(pick<0);
     if ~isempty(i), pick(i)=(n+1)+pick(i); end
  end

  if ~isempty(pick)
     if ischar(pick), eval(sprintf('ii=ii(%s);',pick));
     else
        i=find(pick>n | pick<1);
        if ~isempty(i), wblog(2,'WRN',...
          'pick out of range (skip %g)',numel(i),n);
           pick(i)=[];
        end
        ii=ii(pick);
     end
     n=length(ii);
  end

  if ~isempty(pickX)
     ii(pickX)=[]; n=length(ii);
  end

  if ~n
     legend off ; if ~nargout, clear lg; end
     return
  end

  ll=lh(ii); nn=nn(ii);

  [lg]=legend(ll,nn{:},varargin{:},'AutoUpdate','off');

  if bitand(erase,2)
     c=[1 1 1]-1E-12;
     if isnumeric(lg)
          set(lg,'Color','w','XColor',c,'YColor',c)
     else set(lg,'Color','w','EdgeColor','none');
     end
  else
     legend('boxoff');
  end

  if ~isempty(dx), mvaxis(lg,dx); end

  if rmold
     h0=findall(groot,'Type','axes','Position',get(lg,'Position'));
     if numel(h0)
        if 1, delete(h0);
           t=sprintf(',%.2f',get(lg,'Position'));
           t=sprintf('legdisp:lg[%s]',t(2:end));
           wblog(' * ','got %g legend(s) at %s!',numel(h0),t);
        end
     end
  end

  if ~detach && ~bitand(erase,1) && ...
     isempty(xl) && isempty(dy) && isempty(xsc) && isempty(ysc)
     if ~isempty(fs), set(lg,'FontSize',fs); end
     setax(ah); if ~nargout, clear lg; end
     return
  end

% -------------------------------------------------------------------- %
  lg_=lg; t2=zeros(1,n);
  lg=axes('Position',get(lg_,'Position'));

  if isempty(fs), fs=get(lg_,'FontSize'); end
  topt={topt{:},'FontSize',fs,'Tag','leg:text'};

  los={
     'LineStyle','LineWidth','Color',...
     'Marker','MarkerSize','MarkerEdgeColor','MarkerFaceColor'
  };

  to={'Tag','leg:line'};

  for i=1:n, h=ll(i); lox=get(h,los); y=n-(i-1);
     q={los{1:3}; lox{1:3}}; 
     l2(i)=plot([-2 0],[y y],q{:},to{:});
     if i==1, hold on
        axis([-2.5 5, 0.5 n+0.5]);
     end
     if ~isequal(lox{4},'none')
        q={los{3:end}; lox{3:end}}; plot(-1,y,q{:},to{:});
     end
     t2(i)=text(0.5,y,[nn{i} '^{}'],topt{:});
  end

  xy=get(t2,'Extent'); if iscell(xy), xy=cat(1,xy{:}); end
  axis([-2.5, 0.5+1.2*max(xy(:,3)), [1 n]+[-.5 .5]*max(xy(:,4))]);

  setuser(lg,'Parent',ah);
  set(lg,'Layer','bottom');

  if 0
     t=sprintf(',%.2f',get(ah,'Position'));
     t=sprintf('legdisp:ah[%s]',t(2:end));

     h0=findall(groot,'Type','axes','Tag',t);
     if ~isempty(h0), t
        wblog('WRN','got %g user legend(s) for given axis set',numel(h0));
     end
     set(lg,'Tag',t);
  else
     set(lg,'Tag','leg:detached');
  end

  if bitand(erase,2)
     setax(lg); box on
     set(lg,'XColor',[1 1 1]-1E-12,'YColor',[1 1 1]-1E-12,'Visible','on',...
     'XTick',[],'YTick',[])
  else
     if bitand(erase,1), set(t2,'BackgroundC','w','Margin',1E-3); end
     axis off
  end

  if ~isempty(dy), leg_mvtext(lg,dy); else
     for i=1:n, dy=getuser(ll(i),'leg_dy');
        if ~isempty(dy), h=t2(i);
           if numel(dy)==1, dy=[0 dy 0]; else dy(end+1:3)=0; end
           set(h,'Pos',get(h,'Pos')+dy);
        end
     end
  end

  if ~isempty(xsc) && ~isequal(xsc,1)
     if numel(xsc)==2, set(t2,'Units','data');
        if iscell(xsc)
             set(lg,'XLim',xsc{2}); xsc=xsc{1};
        else set(lg,'XLim',[0 1/xsc(2)]); end
        set(t2,'Unit','norm')
     end
     p=get(lg,'Pos'); x=(p(1)+p(3)/2) + [-0.5 0.5]*(p(3)*xsc(1));
     set(lg,'Pos',[x(1), p(2), diff(x), p(4)]);
  end

  if ~isempty(ysc) && ~isequal(ysc,1)
     if numel(ysc)==2, set(lg,'YLim',0.5+[-1 1]*(0.5/ysc(2))); end
     set(t2,'Units','data');
     p=get(lg,'Pos'); y=(p(2)+p(4)/2) + [-0.5 0.5]*(p(4)*ysc);
     set(lg,'Pos',[p(1), y(1), p(3), diff(y)]);
     set(t2,'Unit','norm')
  end

  if ~isempty(xl), set(lg,'Xlim',xl); end

  setax(ah); legend hide
  if ~nargout, clear lg; end

end

