#!/usr/bin/perl -w
# simple perl script that wraps the perl function realpath
# into a shell command in case that the linux command realpath
# is not available there (e.g., used by matlab_setup.sh)
# Wb,Jan10,19

  use Cwd 'realpath';

  my @ff=@ARGV;
  foreach (@ff) { $_=realpath($_); }
  print join(' ',@ff);

