
% ==================================================================== %
% DMRG launch script / based on matlab class @Hamilton1D
% AW (2014-2018)
% ==================================================================== %

if isset('CONT') % CONTINUE_DMRG

  l=length(NKEEP);
  if isw==l
	 wblog(' * ','using automated sqrt(2) increase in Nkeep');
	 NKEEP=[NKEEP, round(NKEEP(end)*(2.^(1:CONT)/2))];
  elseif isw>l
	 error('Wb:ERR','\n   ERR invalid isw=%g/%g !?',isw,l);
  end

  isw1=isw+1; nsw=numel(NKEEP);

  fprintf(1,'\n NKEEP = [ ...%s ] (%g)\n',...
	 sprintf(' %g',NKEEP(isw1:end)),nsw);

  CONT_=CONT; clear CONT

else % !CONTINUE_DMRG

% setdef('wsys','Spin1-AKLT');
  if ~isset('wsys')
     wsys='Spin1-AKLT';   % by default, chain with open boundary
     setdef('alpha',0.3); s=sprintf('(spin S=1 AKLT at alpha=%g)',alpha);
     banner('box',['running DMRG for default model ' s]);
  end

  isw1=1;

  ismcc=(ismcc || isdeployed);
  if ~ismcc, cto lma; end
  savedat=(isbatch || isdeployed);

  if ~isset('odir')
     if ~ismcc
          odir=[getenv('LMA') '/DMRG'];
     else odir='./DMRG'; end
     if ~exist(odir,'dir'), system(['mkdir ' odir]); end
  end

  Imain=mlinfo;
  if exist('varargin','var') % Wb,Jul29,17
     Imain.varargin=varargin;
     Imain.started=datestr(now);
     Imain.finished='';

   % add simple `version-indicator'
   % by saving status of ctf-archive generated by MCC
     Imain.ctf=dir('./*.ctf'); % Wb,Jan17,18
  end

% tflag = test flag
  setdef('use_endspins',0,'NPsi',0,'tflag',0); 

% threshold in weights to discard in reduced density matrix
% i.e. singular values squared
  setdef('rtol',1E-24');

  onrg={};

% if not specified / left emtpy, this stores data in memory
% (global workspace) rather than in a local file structure
  ofout={};

% NB! initNKEEP also initializes Nkeep=NKEEP(1)

% clear J* % safeguard

  switch wsys
  % ================================================================ %
    case {'Heisenberg'}
  % ================================================================ %
      setdef('L',32,'nk1',3,'Qtot',0);
      initNKEEP;

      setdef('qloc',1,'J',1);
      oham={L,'sym','SU2'}; setopts(oham,qloc);

    % 2nd column in J specifies Jz
      if isvar('Jz') && ~isempty(Jz) && Jz~=1
         oham{3}='Spin'; % uses all-abelian
         if size(J,2)==1, J(2)=Jz; 
         else setopts(oham,Jz);
         end
      end

      if isset('J'), setopts(oham,J); end
      if isset('B'), setopts(oham,B); end

      ofout={'fout',[odir '/DMRG_' wsys]};

      [HAM]=Hamilton1D('Heisenberg',oham,ofout{:});

      L=numel(HAM.mpo);
      if tflag==2, wblog('TST','%g return',tflag); return; end

      [H0]=initNRG(HAM,'Nkeep',Nkeep,'-v',onrg{:}); HAM

  % ================================================================ %
    case 'Spin1-AKLT'
  % ================================================================ %

      setdef('qloc',2); % by default: use spin S=1 (qloc=2S=2)

    % alpha is strength of biquadratic term
    %    alpha=0     plain Heisenberg Hamiltonian
    %    alpha=1/3   AKLT Hamiltonian with simple MPS ground state
      if isset('ph1') && isset('ph2'), alpha=[]; % -> cos(ph), sin(ph)
      else
       % setdef('alpha',1/3); % exact ground state within first DMRG sweep
         setdef('alpha',0.3); % slightly detuned from exact AKLT point
      end

      setdef('L',32,'nk1',2,'nk2',6);
      initNKEEP

    % target multiple multiplets / states
      if isset('NPsi') && NPsi>1, onrg={onrg{:},'NPsi',NPsi}; end
      if isvar('Qtot')
         onrg={onrg{:},'Qtot',Qtot};
      end

      oham={'qloc',qloc};

    % check for end-spins
      if isset('use_endspins') && qloc~=1, setdef('qend',1); end
      if isset('qend')
         L=L+2; oham={oham{:},'qend',1};
      end

    % check for periodic boundary condition
      if isset('perBC')
           n=L; oham{end+1}='-perBC';
      else n=L-1; end

      if alpha
         J=repmat([1,alpha],n,1);
      elseif isset('ph1') && isset('ph2')
         wblog(' * ','using phi=pi*[%g .. %g]',ph1,ph2); 
         ph=pi*linspace(ph1,ph2,L-1)';
         J=[cos(ph), sin(ph)];
      else J=repmat([1],n,1); % plain Heisenberg chain
      end

      ofout={'fout',[odir '/DMRG_' wsys]};

      [HAM]=Hamilton1D('Heisenberg',{J,'sym','SU2',oham{:}},ofout{:});

      L=numel(HAM.mpo);
      if tflag==2, wblog('TST','%g return',tflag); return; end

      [H0]=initNRG(HAM,'Nkeep',Nkeep,'-v',onrg{:}); HAM

  % ================================================================ %
    case {'HBL-SU2'} % Heisenberg ladder
  % ================================================================ %

      sym='SU2'; qloc=[1];

      if isvar('Jp') && numel(Jp)>1
         if norm(diff(Jp))==0, Jp=Jp(1);
         elseif numel(Jp)==2 && ~isset('Jp1') && ~isset('Jp2')
            Jp1=Jp(1); Jp2=Jp(2); Jp_=Jp; clear Jp
         else whos J*; error('Wb:ERR','\n   ERR invalid usage');
         end
      end

    % NB! uniform ladder is in a gapped phase for Jp>0 (likely AKLT)
    % Nkeep=60 multiplets => discareded weight < 1E-14 (!)
    % <e0>=-1.150879399567(4) // Wb,Aug28,15

      setdef('L',32,'nk1',3,'nk2',8);
      initNKEEP

      J=[1,1];
      if isvar('Jp') && numel(Jp)==1, J(2)=Jp;
      elseif isvar('Jp1') && isvar('Jp2')
         if isset('perBC'), error('Wb:ERR',...
           '\n   ERR invalid usage (Jp1/2 with perBC !?'); end
         J=repmat(J,L,1);
         J(:,2)=linspace(Jp1,Jp2,L);
      end

      ofout={'fout',[odir '/DMRG_' wsys]};
      
      if isset('L'), oham={L}; else oham={}; end
      if isset('J'), oham={oham{:},'J',J}; end
      if isset('perBC'), oham{end+1}='-perBC'; end

      oham={oham{:},'sym',sym,'qloc',qloc};
      if isset('qend'), oham={oham{:},'qend',qend}; end

      onrg={'-v','Nkeep',Nkeep};
      if isset('NPsi') && NPsi>1, onrg={onrg{:},'NPsi',NPsi}; end
      if isvar('Qtot') % && ~isempty(Qtot),
         onrg={onrg{:},'Qtot',Qtot};
      end

      [HAM]=Hamilton1D('HsbgLadder',oham,ofout{:});
      if tflag==2, wblog('TST','%g return',tflag); return; end

      [H0]=initNRG(HAM,onrg{:}); HAM

  % ================================================================ %
    case 'TBChain' % tight binding chain of 1 spinless flavor
  % ================================================================ %

      setdef('L',32,'nk1',3,'nk2',7); 
      initNKEEP

      setdef('NC',1); % by default single (i.e. spinless) flavor
      oham={L,'NC',NC};

      if isset('perBC'),   oham{end+1}='-perBC'; end
      if isset('randcpl'), oham{end+1}='-rand'; end

      % open BC
      % +---+-------+---------------+------------------------------+
      % | L | Nkeep | e0x           | rel. error to exact result   |
      % +---+-------+---------------+------------------------------+
      % | 32     64 |-0.625512121890  <1E-9                        |
      % | 32    128 |   -- " --       3E-12                        |
      % +---+-------+---------------+------------------------------+
      % periodic BC
      % +---+-------+---------------+------------------------------+
      % | L | Nkeep | e0x           | rel. error to exact result   |
      % +---+-------+---------------+------------------------------+
      % | 32     64 |-0.634573149226  2E-04 1 )   1E-04 2 )        |
      % | 32    128 |   -- " --       1E-05 1 )   4E-06 2 )        |
      % | 32    256 |   -- " --       1E-09 1')   1E-09 2')        |
      % | 32    512 |   -- " --       3E-12 1')   4E-12 2')        |
      % | 32   1024 |   -- " --                   5E-14 2 )        |
      % +---+-------+---------------+------------------------------+
      % L=6; NKEEP=[4 8 16]; % e0/|t|=-0.6666666666666667 = -2/3
      %
      % 1 ) using long-range bond
      % 1') using long-range bond + double sweep
      % 2 ) using interleaved setup for perBC
      % 2') using interleaved setup for perBC + double sweep
      % => interleaved setup is more efficient for smaller Nkeep,
      %    i.e. does not miss the long-range bond, but eventually
      %    the accuracy is comparable
      % Wb,Sep21,17

    % ofout={'fout',[odir '/DMRG_' wsys]};

      onrg={'Nkeep',Nkeep,'-v'};
      if isset('NPsi') && NPsi>1
           onrg={onrg{:},'NPsi',NPsi};
      else onrg={onrg{:},'Qtot',[fix(NC*L/2), zeros(1,NC-1)]};
      end  % assuming half-filling for Qtot

      [HAM]=Hamilton1D('tightbinding',oham,ofout{:}); %,'t',t);
      [H0]=initNRG(HAM,onrg{:}); HAM

      H=HAM.info.mpo.H; ee=eig(H);
      E0x=NC*sum(ee(find(ee<0))) / L;

  % ================================================================ %
    case {'TBLadder'} % tight binding ladder
  % ================================================================ %

      setdef('L',32,'nk1',3,'nk2',7); 
      initNKEEP

      setdef('NC',1); % by default single (i.e. spinless) flavor

      oham={L,'NC',NC};
      if isset('perBC'),   oham{end+1}='-perBC'; end

      ofout={'fout',[odir sprintf('/DMRG_TB%g_Ladder',NC)]};

      [HAM]=Hamilton1D('tb_ladder',oham,ofout{:});

      if tflag==2, wblog('TST','%g return',tflag); return; end

      [H0]=initNRG(HAM,'Nkeep',Nkeep,'-v','Qtot',[NC*L, zeros(1,NC-1)]); HAM
    % assuming half-filling => Qtot = (NC*L/2) x (2 for ladder)

      H=HAM.info.mpo.H; ee=eig(H);
      E0x=NC*sum(ee(find(ee<0))) / (2*L);

  % ================================================================ %
    case {'Hubbard'} % Hubbard lattice
  % ================================================================ %

      if isset('perBC')
           setdef('Lx',32,'nk1',3,'nk2',7); oham={'--perBC'};
      else setdef('Lx',32,'nk1',3,'nk2',7); oham={};
      end
      initNKEEP; % also inits Nkeep=NKEEP(1)

      setdef('NC',1);

      oham={Lx,'NC',NC,oham{:}};
      oham=setopts(oham,'Ly?','tx?','ty?','U?');
      if isset('mu') oham=[oham {'mu',mu}];
      else oham{end+1}='--ph'; end

      if isset('thub'), oham={oham{:},'t',thub}; end
      if isset('use_spin' ), oham{end+1}='--spin'; s='S'; else s=''; end
      if isset('u1_charge'), oham{end+1}='--U1charge'; end

      ofout={'fout',[odir sprintf('/DMRG_%sHub%g',s,NC)]};

      onrg={'Nkeep',Nkeep,'-v'};

	% NB! cannot know/fix Qtot yet even for mu~0 since U
	% may not be specified yet, e.g., by taking default value
	% Qtot=[] => pick low-energy symmetry sector automatically
	% [since in spinless case, charge accumulates]
	  q=[]; if isset('Qtot'), q=Qtot; end
      onrg={onrg{:},'Qtot',q};
      if isset('NPsi') && NPsi>1, onrg={onrg{:},'NPsi',NPsi}; end

      [HAM]=Hamilton1D('Hubbard',oham,ofout{:});

      L=numel(HAM.mpo);
      if tflag==2, wblog('TST','%g return',tflag); return; end

      [H0]=initNRG(HAM,onrg{:}); HAM

      if HAM.info.param.U==0
         H=HAM.info.mpo.H; ee=eig(H);
         E0x=NC*sum(ee(find(ee<0))) / length(HAM);
         if isset('use_spin'), E0x=2*E0x; end
      end

    otherwise
    error('Wb:ERR','\n   ERR invalid switch'); 
  end

% ==================================================================== %

  if savedat
     if isset('mat_user') % e.g. job tag // Wb,Jan24,16
        mat=mat_user;
     elseif isset('mtag')
        mat=sprintf('%s_%s_%s',wbstamp,mfilename,mtag);
     else
        mat=sprintf('%s_%s_%s',wbstamp,mfilename,wsys);
        if isset('w')
           if ischar(w), mat=[mat w];
           elseif isnumber(w)
              if mat(end)>='0' && mat(end)<='9'
                   mat=sprintf('%s-%g',mat,w);
              else mat=sprintf('%s%g',mat,w); end
           else w, wblog(' * ','ignoring ''w'' with mat file name !?'); end
        end
     end
     save2(mat);
  end

  if numel(NKEEP)<9, s=''; else s='\n =>'; end
  fprintf(1,[' => Total of %g sweeps at NKEEP =' s ' [%s ]\n\n'],...
     numel(NKEEP), sprintf(' %g',NKEEP));

  if tflag<0, NKEEP=NKEEP(1);
  elseif tflag
     wblog('TST','%g return',tflag);
     return
  end

end % !CONTINUE_DMRG

% ==================================================================== %

  nsw=numel(NKEEP);
  HAM.info.sweep.nsw=nsw; % for logging purposes only // Wb,Aug15,16
  HAM.info.sweep.rtol=rtol;

  for isw=isw1:nsw, Nkeep=NKEEP(isw);

     HAM.info.sweep.Nkeep=Nkeep;
     HAM.info.sweep.isw=isw;

     if 0 && isw==1, o={'-t'}; else o={}; end

   % =========================================================== %
   % also return RR for entanglement flow diagram // Wb,Feb24,16
   % as well as diagonalized block Hamiltonian EE // Wb,May16,17
     [r2,E0,Il,HAM,RR,EE]=sweepPsi(HAM,o{:});
   % =========================================================== %

     L2=length(HAM.mpo);
     if ~isequal(size(Il),[L2,2]) || isemptystruct(Il(2))
      % may have restarted sweep -> fix missing data from HAM(k).info
        [Il,RR]=fix_Il_data(HAM,Il,RR);
     end

     q=rmfield(Il,'rr');
     if isw>1
          IL(:,:,isw)=q;
     else IL=q; end

   % local energy added to block may vary along sweep;
   % the total energy E0 must decay monotonically up to truncation errors
   % e0=getdatafield(Il,'e0','-q');
     e0=getdatafield(Il,'E0','-q'); i1=ceil(L2/3); i2=L2-i1+1;
     q=reshape(e0(i1:i2,:)',[],1);

     wblog(' * ','sweep %g/%g : <e0>=%s (@ %.3g)',...
       isw,nsw,num2str2(mean(q),std(q)),r2);

   % NB! ensure that local data is not automatically deleted
   % for long running cluster jobs // Wb,May31,17
     if ~isempty(regexp(pwd,getenv('LBIN')))
        wblog(' * ','touching current directory %s',repHome(pwd));
        system('find . -type f -exec touch -a {} \;');
     end

     if isfield(Imain,'finished') % Wb,Jul29,17
        Imain.finished=datestr(now);
     end

     if savedat
        save2(mat,'-f');
        if isw>1
           system(sprintf('pstime.pl %g',getpid));
        end
     end
  end

  if isset('E0x') % isequal(wsys,'tb1') || isequal(wsys,'tb2')
     e=(E0(1)-E0x)/abs(E0x); fprintf(1,'\n');

     if e>0 && e<1E-3, t=' * '; else t='WRN'; end
     wblog(t,['ground state energy exact to within %.4g\n' ... 
       '> DMRG : %16.12f\n> exact: %16.12f'],e,E0(1),E0x);
  end

% plot(HAM)
% plotDMRG

